version: '3.7'

networks:
    cockpit-core-net:
        external: true

services:
    therap-score-rules-widget:
        image: 'glintt/cockpit-therap-score-rules-widget:$VERSION'
        networks:
            - cockpit-core-net
        deploy:
            placement:
                constraints:
                    - node.labels.role.application == true
            mode: replicated
            replicas: ${FIXED_REPLICAS:-2}
            update_config:
                delay: 10s
                failure_action: rollback
                order: start-first
            rollback_config:
                order: start-first
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
        healthcheck:
            interval: 30s
            retries: 10
            test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:80/
    therap-score-rules-widget-setup:
        image: glintt/cockpit-kong-service-register:0.2.0
        networks:
            - cockpit-core-net
        environment:
            - PROJECT=therap-score-rules-widget
            - ROUTE=/therap-score-rules-widget
            - TAG=widget
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
